### ISSUE TITLE
Implicit memoize cache limit considered harmful

### ISSUE THREAD

**Issue by karczews** [tomtom-international/kotlin-tools#23]
I've noticed that the implicit cache limit was added to `memorize` regardless of all the discussions. As said before, using memorize with implicit limit might be a bit confusing for those who worked with function memorization before.
Let's take a look at other libraries like guava or arrow - why didn't they use any limit?
Because you don't need one. If you look at a function in a mathematical way, if you can evaluate function domain (possible input values), you can evaluate the cache size. By controlling the function domain, control the cache size - thus no limiter is required. ex. 
- `(Boolean?) -> Any` <- 3 possible input values - no harm in skipping the limit. 
- given `enum E { A, B }`, with `(E) -> Any` - 2 possible input values atm, no harm skipping limit. Even if enum grows in the future, you don't even need to update the limit because you are using an unlimited version.

It might not be even desired in some cases - ex. our limit is set as integer, however, if you know that your function domain exceeds max integer, you might be willing to go with the unlimited version. The unlimited version can be also optimized as it does not require LRU cache behaviour.

Now, I do understand that while kotlin do support functional programming paradigm to a certain degree, most of the developers think about development in the imperative or procedural way and we want to shield them from errors. But I do not understand how setting implicit 1000 limit can help with that. Can 1000 really help here? We can probably cache 1000 integers with ease but if function produces ex. 1000 4k bitmaps then we may still have a problem. By enforcing the use of explicit limit, we are forcing them to think about what is being cached. Right now we are offering some kind of *safe* illusion that people might be tempted to actually use in production since they won't be bothered possible results of their action thinking: "ow well, the library will somehow handle that so the cache won't go rampage". That's a false safety illusion that can backfire easily.

Pros:
+ convenience for quick prototyping

Cons:
- confusing for people used to unlimited memoize
- unable to use with function domain where count exceeds max integer
- tempting to use in production by providing safety illusion

Base on the above, it seems that drawbacks outweigh the benefit of added convenience. I suggest either remove default cache value or add back the unbounded memoize.

**Comment by rijnb** [comment]
The reason for adding for adding a default limit is: convenience at no loss of safety. I will try to explain the arguments for keeping a sensible default size and why it does not pose a safety risk.

- A developer never uses an unbound cache to actually cache an unbound number of values. That would overflow memory. That goes for other cache libraries as well. Perhaps the develop has no clue on what a reasonable cache size should be. Providing some form of default is convenient in that case. Using ‘unbound’ as a default is a bit of a risk. Using a limit does not impose a safety risk, because worst case it will simply degrade performance, if the cache size should be bigger than the default. There are no other side effects than that. Whether or not 1000 is a good choice is debatable. As the cache is not allocated in advance, a larger value wouldn’t hurt, probably.

- If a developer needs a bigger cache size than the default, he/she can simply providing the maximum size. Or even use `Integer.MAX_VALUE` to simulate an unbound cache (not recommended).

If we look at the safety cases, we disintiguish:
- An application uses a unlimited number of input variations and specifies no cache limit:
  - if the cache is unbound: will cause crash
  - if the cache is bound: OK, although degradation occurs after some time
- An application uses a limited number of input variations and specifies no cache limit:
  - if the cache is unbound: OK, although degradation may occur if speified size < variations
  - if the cache is bound: OK, although degradation may occur if implied size < variations

As you can see, the specified default removes 1 safety issue and no safety issues are added.

The one valid argument against having a default limit is that some other libraries, like Guava cache, may actually provide unbound caches. For safety, it’s best to either keep the default maximum or remove it altogether. I will consider if the argument of ‘doing what Guava does’ is strong enough, or whether the convenience of a reasonable default is stronger.

**Comment by karczews** [comment]
Regardless of provided default limit, its value will be debatable - only removal of default value will fix it. Even though it was added for safety reason, without knowing function's codomain, I'd consider any value as unsafe.
The issue about memoizing more than integer value can hold is still unaddressed - Integer.MAX_VALUE is not an answer.
For now I'd vote for removal of default value and wait till the unbounded version gets more input/interest/discussion. Perhaps even a different strategy/policy can be thought of for handling memoization without specifying the limit explicitly.

Based on above, saving developer from providing single integer is not a strong argument for having this default value. I do value the convenience however not at cost of inconsistency with API around the world.
